# Generated by Django 3.0.3 on 2020-02-03 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('payment_id', models.CharField(max_length=64)),
                ('token', models.CharField(max_length=500)),
                ('price_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('N', 'New'), ('S', 'Success'), ('C', 'Cancel')], max_length=1)),
            ],
        ),
    ]
